In [2]:
# Melakukan import data dari file excel (.xlsx) dan melihat sekilas isi data
import pandas as pd 
db = pd.read_excel('C:/Users/AsusUser1827/Documents/ESA TAURAN/DATASET/FIFA21 - Insight Pemain Sesuai Kriteria/Career Mode player datasets - FIFA 15-21.xlsx')
db.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,33,1987-06-24,170,72,Argentina,FC Barcelona,...,66+3,65+3,65+3,65+3,66+3,62+3,52+3,52+3,52+3,62+3
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,35,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,54+3,54+3,54+3,61+3
2,200389,https://sofifa.com/player/200389/jan-oblak/210002,J. Oblak,Jan Oblak,27,1993-01-07,188,87,Slovenia,Atlético Madrid,...,32+3,36+3,36+3,36+3,32+3,32+3,33+3,33+3,33+3,32+3
3,188545,https://sofifa.com/player/188545/robert-lewand...,R. Lewandowski,Robert Lewandowski,31,1988-08-21,184,80,Poland,FC Bayern München,...,64+3,65+3,65+3,65+3,64+3,61+3,60+3,60+3,60+3,61+3
4,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Júnior,28,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,67+3,62+3,62+3,62+3,67+3,62+3,49+3,49+3,49+3,62+3

In [44]:
#Mencari kiper dengan tinggi badan minimal 180 dan berkebangsaan Germany dengan umur tidak lebih dari 25 tahun sebagai kiper cadangan dan ranking liganya maks 3 

kiper_muda = db[(db['height_cm'] >180) & (db['nationality'] == 'Germany') & (db['age'] <= 25) & (db['player_positions'] == 'GK') & (db['league_rank'] <= 3) & (db['goalkeeping_reflexes']) & (db['goalkeeping_kicking'] >70) & (db['club_name'] !='Manchester City')]
kiper_muda.sort_values(['age'], ascending = True)  
kiper_muda[['long_name']]

# Dari proses filter, maka kita menemukan pemain sesuai dengan kriteria yang diperlukan oleh Manchester United dengan umur

               long_name
1513     Alexander Nübel
4000  Julian Pollersbeck
5655    Michael Zetterer
6642      Marvin Schwäbe

In [43]:
#Mencari Bek dengan kualitas kontrol bola yang baik, mau berapapun umurnya. 

bek_kontrol = db[(db['player_positions'].str.contains('CB')) & (db['skill_ball_control'] >80) & (db['club_name'] !='Manchester City')]
bek_kontrol[['long_name', 'skill_ball_control', 'release_clause_eur']]
bek_kontrol[['long_name']]

                  long_name
14      Sergio Ramos García
55             Mats Hummels
132  David Olatukunbo Alaba
254             Daley Blind

In [45]:
#Mencari Gelandang Bertahan dengan visi bermain, teknik intercept, dan skill long-passing yang baik

gelandang_bervisi = db[(db['player_positions'].str.contains('CDM')) & (db['mentality_vision'] >80) & (db['mentality_interceptions'] >80) & (db['skill_long_passing'] >80) & (db['club_name'] !='Manchester City')]
gelandang_bervisi[['long_name']]

                             long_name
20                      Joshua Kimmich
42            Sergio Busquets i Burgos
50                      Marco Verratti
56              Jordan Brian Henderson
92      Thiago Alcântara do Nascimento
124                Lucas Pezzini Leiva
125                        Axel Witsel
195  Charles Mariano Aránguiz Sandoval
308         Frederico Rodrigues Santos

In [67]:
# Mencari striker muda dengan kriteria umur dibawah 21 tahun, memiliki umpan / crossing yang baik, skill dribbling yang baik, dan stamina yang sangat baik 

striker_muda = db[(db['player_positions'].str.contains('RW', 'LW')) & (db['age'] <=21) & (db['attacking_crossing'] >75) & (db['skill_dribbling'] >75) & (db['power_stamina'] >75)]
striker_muda

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club_name,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
6,231747,https://sofifa.com/player/231747/kylian-mbappe...,K. Mbappé,Kylian Mbappé Lottin,21,1998-12-20,178,73,France,Paris Saint-Germain,...,67+3,63+3,63+3,63+3,67+3,63+3,55+3,55+3,55+3,63+3
1500,246669,https://sofifa.com/player/246669/bukayo-saka/2...,B. Saka,Bukayo Saka,18,2001-09-05,178,65,England,Arsenal,...,69+2,65+2,65+2,65+2,69+2,67+2,59+2,59+2,59+2,67+2